### PR TITLE
Specify the output directory to run tests

### PR DESCRIPTION
**Pull request by andrewchaa**

### CODE REVIEW

**Comment by mbdavid** [comment]
Hi @andrewchaa, this pr are to fix travis CI ?

**Comment by andrewchaa** [comment]
Hi @mbdavid 
it was my intention, but after pushing the pr, I learned it was appveyor that was failing, not travis.
if you don't mind, I can create appveyoor.yml to fix the CI

**Comment by mbdavid** [comment]
Hi @andrewchaa, will be fantastic. I'm not expert in CI and aways get "red" alert... i spend long time to fix, but back again...

**Comment by andrewchaa** [comment]
No problem. I'll work on it.

**Pull request closed without merging**
