### PR TITLE
New Connection String Parsing

### PR DESCRIPTION
**Pull request by falahati**
Regex replaced by manual enumeration of connection string characters for more flexibility

### CODE REVIEW

**Comment by falahati** [comment]
This commit needs your work to solve conflicts with older version. Sry about that, this happend cuz of reverting the changes and me being lazy and not creating a new branch. :)

**Comment by mbdavid** [comment]
StringScanner is present in LiteDB main lib and another copy in LiteDB shell. But ok, it's beter not use because next version will not support shell inside main lib (only in shell tool).

**Comment by falahati** [comment]
Well, I need to fix a problem with addresses having space in it and I really need this changes to be able to do so. Can we expect this changes soon? :)

**Comment by mbdavid** [comment]
Hi @falahati, yes. I will release this weekend 2.0.3 fixing minor problems

**Pull request closed without merging**
