### PR TITLE
Add interface to LiteRepository and LiteDatabase

### PR DESCRIPTION
**Pull request by klettier**
#678

Hi,

I just want to be able to mock those classes in my code even if I keep a reference on your library.

Thanks

### CODE REVIEW

**Comment by Lonli-Lokli** [comment]
Why did it get closed and not merged?

**Comment by klettier** [comment]
> Why did it get closed and not merged?

No one replied so no one seems interested by it...

**Comment by Lonli-Lokli** [comment]
@mbdavid can you merge it please? From my point of view we as developers should have an ability to create unit test, not integration as now.

**Comment by lbnascimento** [comment]
@klettier We intend for this feature to be present in the v5 release, however your commits are not compatible with changes that were made in the structure of LiteDB. Would you mind reimplementing it or should I do it?

**Comment by klettier** [comment]
> @klettier We intend for this feature to be present in the v5 release, however your commits are not compatible with changes that were made in the structure of LiteDB. Would you mind reimplementing it or should I do it?

I can do it if you can wait until the end of the week ?

**Comment by lbnascimento** [comment]
@klettier Sure, no problem. Thanks!

**Comment by klettier** [comment]
Like in my previous PR [I added interfaces](https://github.com/klettier/LiteDB/tree/feature/add-interfaces) on **LiteDatabase**, **LiteCollection**

Not like in my previous PR I added one to  **LiteRepository**, is that ok for you ?

I wonder if I should add one to **LiteStorage** ?

I have one failing test that is not related to the current addition

```
LiteDB.Tests.Engine.Collation_Tests.Create_Database_Using_Current_Culture
 Source: Collation_Tests.cs line 74
 Duration: 903 ms

Message: 
  Expected d.AsString to be 
  "fi/IgnoreCase" with a length of 13, but 
  "fr-FR/IgnoreCase" has a length of 16, differs near "r-F" (index 1).
Stack Trace: 
  XUnit2TestFramework.Throw(String message)
  TestFrameworkProvider.Throw(String message)
  DefaultAssertionStrategy.HandleFailure(String message)
  AssertionScope.FailWith(Func`1 failReasonFunc)
  StringEqualityValidator.ValidateAgainstLengthDifferences()
  StringValidator.Validate()
  StringAssertions.Be(String expected, String because, Object[] becauseArgs)
  Collation_Tests.Create_Database_Using_Current_Culture() line 84
```

I think we should fix that later.

**Comment by mbdavid** [comment]
Hi @klettier, thanks for your code. I skip this unit test to understand whats going wrong (works here but not in CI). But a question: are your running in windows or macos/linux?

All this classes will be great with interfaces: `LiteDatabase`, `LiteCollection`, `LiteRepository` and `LiteStorage`.

**Comment by klettier** [comment]
> But a question: are your running in windows or macos/linux?

* I'm on windows 10 x64

I will add the interface for ```LiteStorage``` then.

**Comment by klettier** [comment]
PR updated

**Pull request closed without merging**
