### PR TITLE
Added better mutex support for .NET Core (SharedMode)

### PR DESCRIPTION
**Pull request by rexcardan**
Fixed bug where shared mode didn't work with .NET Core - Issue 1707, 1918

### CODE REVIEW

**Comment by haiduong87** [comment]
@rexcardan 
Thank you for making this PR
Can you change to net462, because 461 is end of support now
https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/

**Comment by Inurias** [comment]
Hi, do you think this could also fix https://github.com/mbdavid/LiteDB/issues/1546?

**Comment by rexcardan** [comment]
I think so. I looks like the same symptom.

**Comment by haiduong87** [comment]
@Inurias 
I don't think so, #1546 is another problem

**Pull request closed without merging**
