### PR TITLE
Add failing tests

### PR DESCRIPTION
**Pull request by JKamsker**
That way people could submit prs only containing tests that should work but currently don't

### CODE REVIEW

**Comment by pictos** [comment]
But why? I would say that's better to contributors implementing the test with the actual fix... I believe that kind of test will pollute the test suite

**Comment by JKamsker** [comment]
This would be a benchmark to measure the (hopefully increasing) stability of the library

**Comment by pictos** [comment]
> This would be a benchmark to measure the (hopefully increasing) stability of the library.

can you expand more on this?

> That way we know what the user would expect and we or someone else can fix it if they got the resources for it.

on GitHub we already have `issues` to mark what needs to be worked, and the community interaction on those issues will point us to the highest priority ones. So how having a bunch of failing tests would be a better measurement system than what GitHub already provide to us?

**Comment by pictos** [comment]
can we close this one?

**Pull request closed without merging**
