### PR TITLE
Should fix travis build

### PR DESCRIPTION
**Pull request by RytisLT**
remove unused file that causes travis build to fail

### CODE REVIEW

**Comment by RytisLT** [comment]
need to get my build tools right, I meant of course travis and not maven :)

**Comment by RytisLT** [comment]
fixed commit message, all hail force push :)

**Comment by mbdavid** [comment]
Travis are in a never-finish building...

**Comment by RytisLT** [comment]
Removed the osx build from travis. It lookw like it timed out because unit tests take longer than 10 minutes to execute and during this time no output is written to console so travis assumes that something went wrong and kills the process.

**Pull request merged**
