### PR TITLE
Enables Portable libraries for UWP and old style PCL

### PR DESCRIPTION
**Pull request by szurgot**
Implements Portable Class Library support for LiteDB for UWP/ASP vNext (netcore) as well as older style PCL (PCL)

All changes made in place with conditional #if statements. All tests were linked in the new projects, and removed/#if'd out where there were unsupported features.

NetCore - New style PCL targeting Windows 10 & ASP.NET v5. 
This supports almost all features. The FileDisk and EncryptingDisk service had to be removed, and some reflection code had to be changed, but otherwise is intact. Shell functions are also mostly intact. (Only includes shell functions that are in the package, since you can't get additional assemblies directly in portable code. This could be worked around by having an init function that allows specifying additional assemblies for discovery. (That would be implemented by the consuming package)

I've incorporated this version into a Windows 10 platform in place of a SQLite DB with no discernible impact. It just worked once I swapped out the calls in the data layer.

PCL - Targets a broader setup of platforms, but reduces functionality more. One of the big differences is that this version will only support serialization of public methods.

### CODE REVIEW

**Comment by mbdavid** [comment]
Hi @szurgot, really nice job done here! Thanks a lot. I will run and test your changes and merge after.

To remove FileDisk and use on StreamDisk needs implement changes in StreamDisk. Current implementation are too simple: no journal, no concurrency, no locks... It's used basically to testing (using MemoryStream) or a read only embedded resource.

**Comment by szurgot** [comment]
Admittedly, my app is pretty straightforward, and I did my best to ensure the reads and writes were isolated beforehand, but I was still pleased at how easily it came together. I'm going to look at making a IDiskService for the UWP API, and that can implement locking and journaling for the UWP API.

**Comment by szurgot** [comment]
Updated FileDiskService so that it works in a Universal App. It only allows one program to access the database, but it's pretty quick, and allows access both in the LocalStorage or an arbitrary folder. It could be split out into a separate file, but using conditionals allowed to keep the changes to a minimum.

The next steps for getting this to work better would be sync/async methods but that's a bit more invasive, and not something I'm going to start without good coordination.

**Comment by Cologler** [comment]
Use Expression.Lambda().Compile() to get/set field from entity. This is fastest accessor in PCL.

you can found example from my repo:

* [PropertyExtensions](https://github.com/Cologler/jasily.cologler/blob/master/Jasily.Core/Reflection/PropertyExtensions.cs)
* [FieldExtensions](https://github.com/Cologler/jasily.cologler/blob/master/Jasily.Core/Reflection/FieldExtensions.cs)

and found performance test result from [README](https://github.com/Cologler/jasily.cologler/blob/master/Jasily.Core/Reflection/README.md)

**Comment by LordLobo** [comment]
Any chance this will be merged into the master branch and pushed to NuGet soon? I'd really like to use LiteDB for the UWP project I'm working on and would prefer not to compile/include it by-hand.

**Comment by mbdavid** [comment]
Hi @LordLobo, to be honest, i´m with no time now to test this merge. If someone made this tests I can merge to master and create a nuget version

**Comment by szurgot** [comment]
What else do you need in order to merge this? There are tests covering both new libraries and it's working fairly well in my small projects.

**Comment by mbdavid** [comment]
Hi @szurgot, it's only out of time to me. I worked in dev branch in some data structure changes and my palns are merge this pull with dev branch. I will try do this next weekend and release rtm v2 version

**Comment by WattsC-90** [comment]
Hi, any word on this PR? Really eager to use the library on my RPI project!:)

**Comment by mbdavid** [comment]
Hi @WattsC-90, merge this pull request is my priority now to release new version. But I made some changes in dev branch and now I merge with master. There is not more auto-merge with this branch... I'm mading file-by-file check changes.

**Comment by mbdavid** [comment]
Work done. Can someone test in a mobile app? And again, thansk @szurgot

**Comment by WattsC-90** [comment]
Man, this is brilliant! Thanks for putting the work in.. One last question, and sorry for not fully understanding the process, but what does this mean for the nuget package? Is it available straight away? Or..?

**Comment by negue** [comment]
I guess I'm too late to tell I'm nearly done with a refactoring to support .net35, .net45 , uwp, winrt, android, ios and mac huh? :(

**Comment by szurgot** [comment]
I've been testing this out, and I'm running into a problem. It looks like the Find methods are opening read transactions that are never closed. (Find in DbEngine and Find in LiteCollection) Because of this, the transaction is never closed, so the level never reaches 0 again so it can write. I'm trying to find a way for it to work correctly with the yield statements, but I haven't sorted it out yet.

**Comment by mbdavid** [comment]
Hi @szurgot, as you can see, I change the way how access datafile to remove Lock/Unlock operations. How did you get this error? Can you reproduce? I'm commit a new test using DiskFile.

**Comment by mbdavid** [comment]
Hi @negue, it's nice to know that. Maby you can help us to improve this version to release v2

**Comment by mbdavid** [comment]
@WattsC-90 it's only on master branch for compile. It's not 100% yet and I will wait one or two weeks before release v2 in nuget.

**Comment by negue** [comment]
@mbdavid Well I had to remove and refactor a lot , so nearly 60% of this pullrequest is "gone" , you'll see once its ready , maybe today but probably tomorrow.

btw the concurrenttest doesn't run in the master-branch, I guess a deadlock (because of no locks and stuff)

**Comment by szurgot** [comment]
Here's a simple test. It will demonstrate how the find leaves a hanging transaction that is never closed, so the insert is never written. I solved this by putting a try/finally in the find.cs file for DbEngine, but that introduces other issues around transactions, and the transaction stack.

            MemoryStream ms = new MemoryStream();

            using (var db = new LiteDatabase(ms))
            {
                var coll = db.GetCollection<StreamTestsClass>("StreamTestsClass");
                // Do a find on a non-existant record
                var val = coll.FindById(new BsonValue(1));

                Assert.IsNull(val, "Empty database should not have record");
                val = new StreamTestsClass() { Id = 1, Value = "Hello" };
                coll.Insert(val);
            }

            using (var db = new LiteDatabase(ms))
            {
                var coll = db.GetCollection<StreamTestsClass>("StreamTestsClass");
                var val = coll.FindById(new BsonValue(1));

                Assert.IsNotNull(val, "Database should contain value from previous session");
            }

**Comment by szurgot** [comment]
I worked with things today, fixed up issues I was seeing, and submitted another push request. If you could take a look at that. It has some tests for the issues (passing now) and a few minor fixes that should make sense.

Can probably close this out now that it's merge in. :)

**Comment by WattsC-90** [comment]
@szurgot
What pr am i looking at now then? Been trying to follow the progress thats all! Thanks

**Pull request closed without merging**
