### PR TITLE
Removed dependency on Reflection.Emit

### PR DESCRIPTION
**Pull request by lee-orr**
I removed Reflection.Emit and replaced it with lambdas, to enable compilation & use in unity for webgl. Should also allow Unity & Xamarin iOS (untested)

### CODE REVIEW

**Comment by mbdavid** [comment]
Hi @lee-orr, nice job. Did you test performance about this? I use Emit because it's fast but require full .NET. I thinking in use compile condition to create 2 version: Full .NET and PCL.

**Comment by lee-orr** [comment]
I haven't had a chance to test performance. It seemed to respond well for my use case, but it's a very limited case.

**Comment by negue** [comment]
Is it possible to extract the Reflection.Emit calls (with an Interface) so that we could enable the use in the full .Net and all others could use the lambda version?

**Comment by gentledepp** [comment]
I think negues idea is very good - if doable.
The reason being that Reflection.Emit is surely much faster, but on the other hand, you cannot use it on platforms such as Xamarin.Android and Xamarin.iOS

**Comment by ToniMontana** [comment]
I have tested this commit on Xamarin.iOS and successfully tested LiteDB in a Xamarin.iOS application. It seems to work. A compile flag to be able to build for different platforms would be very useful.

**Comment by mbdavid** [comment]
There is a new version in master branch that supports Xamarin.iOS. Can someonde test (I have no Xamarin skill)?

**Comment by negue** [comment]
Can be closed now. :)

**Pull request closed without merging**
