### PR TITLE
docs: fix hugo links

### PR DESCRIPTION
**Pull request by viceice**
The relative links at the docs are wrong [here](https://www.litedb.org/docs/indexes/)

### CODE REVIEW

**Comment by viceice** [comment]
https://gohugo.io/content-management/cross-references/

**Comment by viceice** [comment]
Does not work yet. Do i need to rebuild locally and send pr with updated files?

**Comment by lbnascimento** [comment]
@viceice Yes, you need to rebuild after every change

**Comment by viceice** [comment]
ok, so  I'll send a new pr with rebuild

**Pull request merged**
